import{a as w,i as a,S}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const E="47567407-25ef3519c02546aa2529f6321",M="https://pixabay.com/api/",P=15;async function h(e,r=1){try{return(await w.get(M,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:P}})).data}catch(n){throw iziToast.error({title:"Fetch Error",message:`Something went wrong: ${n.message}`,position:"topRight",theme:"dark",backgroundColor:"red"}),n}}function y(e){return e.map(({webformatURL:r,largeImageURL:n,tags:l,likes:t,views:o,comments:s,downloads:L})=>`
        <a class="gallery-item" href="${n}">
          <img src="${r}" alt="${l}" loading="lazy" />
          <div class="info">
            <p><b>Likes:</b> ${t}</p>
            <p><b>Views:</b> ${o}</p>
            <p><b>Comments:</b> ${s}</p>
            <p><b>Downloads:</b> ${L}</p>
          </div>
        </a>
      `).join("")}function k(e){e.innerHTML=""}const v=document.querySelector(".search-form"),c=document.querySelector(".gallery"),q=document.querySelector(".loader"),u=document.querySelector(".load-more");let i=1;const g=15;let m,d="";v.addEventListener("submit",C);u.addEventListener("click",$);async function C(e){if(e.preventDefault(),d=e.currentTarget.elements.searchQuery.value.trim(),!d){a.error({message:"Please enter a search query!",position:"topRight",theme:"dark",backgroundColor:"red"});return}i=1,k(c),p(!1),A();try{f(!0);const{hits:r,totalHits:n}=await h(d,i,g);if(!r.length){a.error({message:"Sorry, there are no images matching your search query.",position:"topRight",theme:"dark",backgroundColor:"red"});return}c.insertAdjacentHTML("beforeend",y(r)),b(),a.success({message:`Found ${n} images!`,position:"topRight",theme:"dark"}),n>g&&p(!0)}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight",theme:"dark",backgroundColor:"red"})}finally{f(!1)}}async function $(){i+=1;try{f(!0);const{hits:e,totalHits:r}=await h(d,i,g);c.insertAdjacentHTML("beforeend",y(e)),b(),i*g>=r?(p(!1),R()):H()}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight",theme:"dark",backgroundColor:"red"})}finally{f(!1)}}function f(e){q.style.display=e?"block":"none",u.disabled=e,u.textContent=e?"Loading...":"Load More"}function p(e){u.style.display=e?"block":"none"}function b(){m?m.refresh():m=new S(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}function R(){c.insertAdjacentHTML("afterend",`<p class="end-message">We're sorry, but you've reached the end of search results.</p>`)}function A(){const e=document.querySelector(".end-message");e&&e.remove()}function H(){const e=c.firstElementChild;if(!e)return;const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
